# Generated by Django 4.1.4 on 2022-12-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='FullName',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(),
        ),
    ]
