# Generated by Django 4.1.4 on 2023-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaceName', models.CharField(max_length=100)),
                ('History', models.TextField()),
                ('LocalTransportation', models.TextField()),
                ('PrivateTransportation', models.TextField()),
                ('RideSharingService', models.TextField()),
                ('EntryFees', models.TextField()),
                ('Stays', models.TextField()),
                ('Photo', models.ImageField(upload_to='static')),
                ('MapPhoto', models.ImageField(upload_to='static')),
                ('MapLink', models.URLField()),
            ],
        ),
    ]
