# Generated by Django 4.1.4 on 2023-04-29 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0004_heritagedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagedetails',
            name='Details',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heritagedetails',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
