# Generated by Django 4.1.4 on 2023-04-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject', '0005_heritagedetails_details_alter_heritagedetails_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagedetails',
            name='Photo2',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='heritagedetails',
            name='Photo3',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='heritagedetails',
            name='Photo4',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='heritagedetails',
            name='Photo5',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='heritagedetails',
            name='Photo6',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='heritagedetails',
            name='MapPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='filepath'),
        ),
    ]
