class HeritageDetails(models.Model):
    Place_id = models.AutoField
    PlaceName = models.CharField(max_length=100)
    Details = models.TextField()
    History = models.TextField()
    LocalTransportation = models.TextField()
    PrivateTransportation = models.TextField()
    RideSharingService = models.TextField()
    EntryFees = models.TextField()
    Stays = models.TextField()
    Photo = models.ImageField(null=True, blank=True, upload_to="static")
    Photo2 = models.ImageField(null=True, blank=True, upload_to="static")
    Photo3 = models.ImageField(null=True, blank=True, upload_to="static")
    Photo4 = models.ImageField(null=True, blank=True, upload_to="static")
    Photo5 = models.ImageField(null=True, blank=True, upload_to="static")
    Photo6 = models.ImageField(null=True, blank=True, upload_to="static")
    MapPhoto = models.ImageField(null=True, blank=True, upload_to="filepath")
    MapLink = models.URLField(max_length=200)
    SuggestedPlaceName1 = models.CharField(max_length=100)
    SuggestedPhoto1 = models.ImageField(null=True, blank=True, upload_to="static")
    SuggestedPlaceName2 = models.CharField(max_length=100)
    SuggestedPhoto2 = models.ImageField(null=True, blank=True, upload_to="static")